package protocol;

public enum EResponse {
    ERROR(0), 
    SUCCESS(1), 
    EMAIL_NOT_FOUND(2), 
    PASSWORD_DOESNT_MATCH(3), 
    REQUIRE_AUTH(4), 
    AUTH_SUCCESSFUL(5),
    REQUIRE_NEW_ACCOUNT(6),
    REQUIRE_PASSWORD_RESET(7),
    DEFAULT_MESSAGE(8),
    REQUIRE_FRIENDLIST(9),
    FRIENDLIST_RESPONSE(10),
    REQUIRE_CHANGE_STATUS(11),
    FRIEND_CHANGE_STATUS(12),
    REGISTRATION_SUCESSFUL(13),
    EMAIL_ALREADY_EXISTS(14),
    FIND_PROFILE_REQUEST(15),
    FIND_PROFILE_RESPONSE(16),
    NEW_FRIEND_REQUEST(17),
    FRIENDSHIP_QUESTION(18),
    ACCEPTED_FRIENDSHIP(20), 
    REFUSED_FRIENDSHIP(21), 
    PENDING_FRIENDSHIP_REQUEST(22),
    PENDING_FRIENDSHIP_RESPONSE(23),
    SEND_MESSAGE(24),
    RECIEVE_MESSAGE(25),
    SEND_TAKE_ATTENTION(26),
    RECIEVE_TAKE_ATTENTION(27),
    REQUEIRE_API_AUTH(28);
   
    public int type;
    
    EResponse(int value){
        this.type = value;
    }
}
